### ISSUE TITLE
Setting NS.node_context.fqdn should be inline with how sds identifies the node

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/commons#687]
Setting NS.node_context.fqdn should be inline with how sds identifies the node

Currently it uses socket.gethostname but in case where a node has multiple ips, this can be confusing..
Or at the best have a mechanism to know the cluster identified name of the node in node_context ..

**Comment by r0h4n** [comment]
@atinmu Need your help here

- My understanding is that the fqdn or ip used for "gluster peer probe" will be the valid fqdn for that node and for tendrl to identify that node
- Since "gluster pool list" shows "localhost" for the peer from which that command is run, what should be the correct way to find out the fqdn (used for peer probe) from the same node.

**Comment by atinmu** [comment]
We need a discussion on this @r0h4n . I'd like to get more details on what's the exact problem here.

**Comment by r0h4n** [comment]
Closing this issue, since Gluster also recommends use of fqdn and so does Tendrl.
