### ISSUE TITLE
Add a new flow called un-manage cluster to remove particular cluster details from tendrl

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/commons#797]
The unmanage cluster is a flow to remove the particular cluster details from tendrl. When a cluster is moved to unmanaged state then tendrl server will stop monitoring the cluster. And information about the particular cluster is permanently removed from the tendrl database. 

Information which is removed from tendrl is:
  * Pre-execution flows:
           1. Create a child job to stop and node-agent and gluster-integration and collectd from all 
               storage nodes in a cluster.
           2. Uninstall gluster-integration and colletd from all storage nodes.
  
    * Main flow execution:
           1. Remove entire cluster info from /cluster/{cluster_id} in etcd
           2. Remove node information for all storage nodes which are all belongs to the unmanaged 
               cluster from /nodes/{node_id}.
           3. Remove all alerts information for the particular cluster from /alert/alerts/{alert_id}, 
               /alert/nodes/{node_id}/, /alert/clusters/{cluster_id}
           4. Remove cluster information for the particualr cluster form graphite.
           5. Remove tag infomation, ip information, detected cluster information from indexes.
           6. Remove network information from global network details for all correspoding storage nodes.

     * Post execution:
            1. Remove graphs from alerting dashbaord 
             2. Restart node-agent from all storage nodes of particular un managed cluster (It will used to show import cluster option again for the particular cluster)

**Comment by GowthamShanmugam** [comment]
@shtripat @nthomas-redhat @nnDarshan @r0h4n comment please

**Comment by shtripat** [comment]
>> Restart node-agent from all storage nodes of particular un managed cluster (It will used to show import cluster option again for the particular cluster)

This should not be done as part of um-manage. Rather at later stage if somebody wants to reimport the cluster, they manually should start node-agent services on the nodes of the cluster and the cluster would start reflecting as a cluster to be imported in tendrl.

**Comment by shtripat** [comment]
So the process flow could be as below

- Create a job in monitoring-integration for un-managing the cluster
- This creates child jobs on participating nodes of the cluster to stop gluster-integration and collectd on those nodes
  - Stop gluster-integration
  - Stop collectd 
- Once child jobs are over, remove the cluster details from ETCD in main flow
  - Delete `/cluster/{int-id}` recursively
  - Delete `/nodes/{node-id}` for all the participating nodes recursively
  - Delete entries `/alerting/nodes/{node-id}` and `/alerting/clusters/{int-id}` recursively
  - Delete detected cluster, tags etc for cluster and its nodes
  - Delete network information from global space
- Finally remove the graphite data for the cluster and its nodes

In this oreder, the details of the cluster and its nodes would be deleted from ETCD but as the node-agents are still running in the nodes, the cluster would reported back as detected cluster to tendrl again.

Also there is no need to delete entries from `/alerting/alerts` for the un-managed cluster and its nodes because they are older alert conditions which were set earlier and should be there as a history.

Later when the cluster gets re-imported (say if admin wants it back), the new set of `/alerting/nodes/{node-id}` and `/alerting/clusters/{int-id}` entries would be created back.

Summary: The un-manage cluster is a main job in monitoring-integration, which internally start node-agent sub jobs for service stops etc. Finally it cleans the entries from centrals store for the cluster and its nodes.

@Tendrl/tendrl-core comments??

**Comment by shtripat** [comment]
Stopping node-agents on the participating nodes of the cluster is not possible as tendrl doesnt have a mechanism to run remote command on the storage nodes. We need at least node-agents to be running for performing any actions.

If user wants not to maintain the cluster at all later, they can stop node-agents manually on the storage nodes as a post action.

**Comment by GowthamShanmugam** [comment]
this approach is LGTM

**Comment by gnehapk** [comment]
@julienlim @mcarrano Request you both to go through the steps and please provide the UX design for un-manage cluster flow. Please let us know if you have any questions.

**Comment by julienlim** [comment]
@GowthamShanmugam @shtripat @gnehapk @r0h4n @mcarrano @Tendrl/tendrl-qe @rghatvis@redhat.com 

First-off thanks for summarizing above what's expected with "Unmanage cluster."  I've tried to summarize my thoughts and questions before we put together any mockups/designs.

Is this about remove cluster or unmanage cluster?
* I use the term “remove” as the cluster will exist after removal and is not getting deleted.  This is similar to moving files into Trash / Recycle Bin (and can be recovered later).
* Typically when the term unmanage gets used, a user will then expect to manage (vs. import) the cluster again at a later date.
* Should this be termed Remove Cluster vs. Unmanage Cluster?  The terminology would be used in the UI and subsequent documentation.

If we keep the Manage / Unmanage terminology, I would summary the following about Manage vs. Unmanage Cluster:
* Manage cluster allows the Tendrl admin to perform the following actions:
    * Enable / disable volume profiling
    * View details about the cluster and its related entities (nodes and volumes)
    * View dashboards for the cluster and its related entities (nodes, volumes, bricks)
    * View alerts an event information about the cluster and its related entities
* Unmanage cluster allows the Tendrl admin to perform the following actions:
    * Import cluster
    * Remove cluster information from etcd and Grafana repository

**User Story**
* As a Tendrl admin, I want to remove 1 cluster, as I no longer want to see information about the cluster in the UI for the following possible reasons:
    * unmanage a cluster temporarily for maintenance reasons
    * verify a cluster can be monitored via Tendrl prior to being put into production use
* As a Tendrl admin, I don’t want to see monitoring detailed information about any unmnaged clusters in the Dashboard, events and alerts related to the cluster, telemetry information about the cluster, log entries for the cluster, and so on, as this will reduce noise and confusion when looking at the UI or when performing troubleshooting.
* As a Tendrl admin, when I unmanage a cluster, I expect the node agent tol be stopped, but it can be used to later by restarting the node agent in order for a cluster to be imported later (to be managed).   Furthermore, the node agent should not restart at next reboot.
    * gluster-integration and collectd agents also are stopped and should not restart at next reboot.
    * This means that an unmanaged cluster will still appear in the Clusters List as a cluster that can be imported.

**Success criteria**
* remove cluster from dashboards (WA and Grafana)
* No cluster entries in the context switcher in the WA UI and Grafana
* A list view entry for the cluster will only exist for importing it, and it will not have any cluster details for the cluster, and no dashboard button/hyperlink.
* No list views for cluster nodes and its related  volumes in the WA UI and Grafana Dashboards
    * If Optimized UX design did not get implemented, then the cluster nodes will appear in the Hosts Listing (but unmanaged and with no dashboard button/hyperlink)
* remove cluster and related information from etcd
* remove cluster and underlying components’ related statistics information from grafana, including graphite and Whisper data files
* Documentation will provide guidance on how to manage the cluster, i.e. through manually starting the various agents (node agent, cluster-integration, collectd) and enable the services to restart at next reboot.

**Assumptions:**
* User can only unmanage 1 cluster at a time.

**Questions:**
* I saw a suggestion that alerts should be kept for unmanaged clusters for historical and audit reasons.  If so, wouldn't Tendrl need to retain some information about the cluster and its entities so the alerts don't show orphaned unique identifiers that user may not understand?

**Suggested UI Workflow Steps**
1. User selects cluster and clicks on Unmanaged.
2. System provides a dialog explaining what will take place and asks for user Yes/No confirmation.
3. If user confirms Yes, Systems logs a job for the execution of the Unmanaged cluster task.  System generates a notification when the job has completed.  If job completes successfully, all traces of the cluster details will no longer be visible in the UI and Dashboards except for the Cluster List (where cluster is ready for import), and Host List (if still exists for all hosts in all clusters).
4. If user answers No, the action is ignored.

Thoughts?  We'll put together some mockups per the suggested UI workflow steps above.

**Comment by shtripat** [comment]
IIUC, there are two flows actually

1. Un-manage the cluster which just makes sure all the cluster details no more visible in UI and grafana dashboards. The cluster is listed as detected cluster (which could be imported later if required)

2. Forget/Remove an un-managed cluster. This makes sure the cluster doesnt even get listed as detected in tendrl UI (effectively this means all the details of the cluster are removed from etcd and graphite DB. Also all the services on the storage nodes like collectd, tendrl-gluster-integration and tendrl-node-agent are stopped and disabled so that they dont get started back on restart of nodes)

Based on this I propose the below changes in tendrl to tackle the flows

UN-MANAGE
1. Stop services collectd and tendrl-gluster-integration on storage nodes and disable them (tendrl-node-agent keeps running on the nodes which makes sure the cluster gets listed as detected cluster)
2. Delete etcd details for the cluster and its participating nodes so that nothing specific to the cluster gets listed in UI
3. Remove the graphite data for the cluster so that nothing specific to cluster gets listed in grafana dashboards
4. Remove the grafana alert dashboards for the cluster

Now in this case all the alerting entries from `/alerting/clusters/{int-id}` and `/alerting/nodes/` get removed but global list of alerts under `/alerting/alerts` remains with the old entries for the un-managed cluster as well (anyway any data older than 2 days would be removed due to TTL).

FORGET/REMOVE
In this flow the tendrl-node-agent service as well is stopped on the storage nodes and disabled. Also any traces of detected cluster in etcd get removed so that cluster doesnt event get listed as detected cluster in UI. In this case later if admin wants to import and manage this cluster, he needs to refer the admin guide for starting and enabling the tendrl services on the storages nodes and then importing the cluster afresh.

Note: In both the un-manage and forget cluster all the old monitoring data maintained with graphite would be lost and once cluster gets imported again, that point onward only monitoring details would be available.

Also we can make sure that only a un-managed cluster should be forgot from UI. Thoughts???

@julienlim @nthomas-redhat @brainfunked @r0h4n share your thoughts on this if the logic looks fine.
@julienlim thanks for detailing it well.

**Comment by GowthamShanmugam** [comment]
@shtripat Only info alerts are removed by ttl, warning alerts are not removed

**Comment by shtripat** [comment]
@GowthamShanmugam in that case as suggested by @julienlim may be we need to find out the deleting alert-ids from `/alerting/clusters` and `/alerting/nodes` and remove them from `/alerting/alerts` as well.

**Comment by julienlim** [comment]
@shtripat +1 on there being 2 flows, i.e. unmanage cluster and remove/forget cluster.  Will provide mockups accordingly along.

@GowthamShanmugam @shtripat @gnehapk @r0h4n @mcarrano @Tendrl/tendrl-qe @rghatvis@redhat.com @brainfunked @nthomas-redhat

**Comment by shtripat** [comment]
@julienlim there is a technical limitation achieving Forget cluster though. We should stop node-agents on storage nodes for forget cluster and disable the service. As tendrl-server doesnt have any other mechanism to run commands on storage nodes (by the time we trigger forget cluster, all other services like collectd, tendrl-gluster-integration etc. would have been stopped on storage nodes and no flows to stop node-agent can be executed).

Even tendrl-anisble cannot be thought of as an option because as part of forget cluster we would need access to etcd for removing the detected cluster details (which would be there after un-managing the cluster).

@brainfunked @nthomas-redhat @r0h4n thoughts, suggestions??

**Comment by julienlim** [comment]
@shtripat @brainfunked @nthomas-redhat @r0h4n what are you suggesting with regards to Forget Cluster?

**Comment by r0h4n** [comment]
Lets use this issue for finishing up "Unmanage Cluster", once done we can think of  "Forget cluster"

Also, the tendrl-node-agent should not be stopped during "Unmanage Cluster". The "Cluster.is_managed" flag should be flipped to "false"

Stopping the tendrl-node-agent should be  part of "Forget cluster" as @shtripat  said.

**Comment by shtripat** [comment]
Ack 👍

**Comment by mcarrano** [comment]
I've added the Unmanage action to the "Concept B" deck here: https://redhat.invisionapp.com/share/8QCOEVEY9

This simply adds a kebab menu to the Clusters list view with 2 actions (Disable Profile and Unmanage) and adds a new dialog to start the Unmanage task and a confirmation. Let me know if you have any questions.

**Comment by shtripat** [comment]
As per latest discussion, as part of this issue, we would be taking care of un-manaage cluster part only. The flow would be performing the below tasks

1. Stop services collectd and tendrl-gluster-integration on storage nodes and disable them (tendrl-node-agent keeps running on the nodes which makes sure the cluster gets listed as detected cluster)
2. Set the flag `is_managed = False` for the cluster in question
3. Archive the graphite data for the cluster so that nothing specific to cluster gets listed in grafana dashboards. The location of the archive for the cluster should be configurable
4. Remove the grafana alert dashboards for the cluster entities like volumes and bricks

@r0h4n @julienlim @nthomas-redhat @mbukatov please review and ack the steps of the flow.

**Comment by julienlim** [comment]
Ack @shtripat 

I would also strongly suggest that we ensure we cover some level of logging (which includes events and alerts accordingly) to indicate when something becomes unmanaged.  Also the spec should cover both all the work including backend, frontend, API, etc.

Thanks.

**Comment by GowthamShanmugam** [comment]
@shtripat shall we close this issue

**Comment by shtripat** [comment]
Yes it can be closed
