### ISSUE TITLE
Retention policy for tendrl data

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#819]
We need to have a retention policies for data maintained within tendrl for graphite and etcd

1. In case of managed cluster how long we should retain graphite data
2. In case of un-managed cluster, what happens to the archived data? Whether we get back the old data when the cluster is managed again or we start having graphite from the time its managed back again
3. How long we keep the alerts and notification data in tendrl central store? Currently we have some default values set for them.
4. If some document impact (need to be documented) when and where to look for archive graphite data. Currently we have plans for having a configurable path where graphite data gets archived in case of un-manage cluster and the same is communicated when a cluster is un-managed in a notification.
5. If we retain the same cluster-id (integration-id) across un-manage and manage back of cluster

Above are few questions which we need clarifications. Tagging required people for the same.

@julienlim @r0h4n @nthomas-redhat @jjkabrown1

**Comment by julienlim** [comment]
@shtripat Here are some of my thoughts to the 5 points above:

(1) & (3) Regarding how long to retain data or rather what should be the Tendrl default retention policy, I've tried to list down what are default retention periods for other products/projects:

* [ManageIQ](https://access.redhat.com/documentation/en-us/reference_architectures/2017/html/deploying_cloudforms_at_scale/capacity_and_utilization#data_retention): 6 months for capacity and utilization data
[Microsoft Azure Application Insights](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-data-retention-privacy): 90 days
* [OpenShift](https://docs.openshift.com/container-platform/3.6/scaling_performance/scaling_cluster_metrics.html): 7 days for Cluster metrics; samples every 15 seconds
* [oVirt](https://www.ovirt.org/documentation/data-warehouse/Application_Settings_for_the_Data_Warehouse_service_in_ovirt-engine-dwhd.conf/):  
Hourly data stored for 60 days and Daily data stored for 5 years; samples every 60 seconds)

Note: for different industries, there may be regulatory rules around retention, e.g. for PCI compliance (PCI DSS Requirement 10.7), audit logs must be kept for 1 year with a minimum of 3 months immediately available for analysis.

We will need to offer configuration for different time periods of the different types of data since there may be different rules/policies around it, and here's my initial thoughts:
* telemetry data (metrics): 60 days or 90 days
* events log (aka notification data): 6 months
* alerts: 2 days (as-is)

For telemetry data, based on graphite archival capabilities, we probably want to fine-tune this further for varying precision.  What is our current default configuration?  It might be worth seeing if https://github.com/ceph/cephmetrics/ had some thoughts on this topic as well.

(2) For the graphite archive data for the unmanaged cluster, maybe we don't bring back the old data but provide instructions / documentation on how to do so if needed.  And, let's see what users say if we need to or not.  

(4) I'll assume we'll communicate this back in some of sort of message that gets logged when the cluster is unmanaged.

(5) Retaining cluster-id (integration-id) for unmanage back to manage cluster is required so that we don't orphan logs (logs, notifications, etc.) that were previously retained (when a cluster became unmanaged).

@r0h4n @nthomas-redhat @jjkabrown1 @Tendrl/tendrl-qe

**Comment by ltrilety** [comment]
@shtripat @julienlim My thoughts about the retention policy are slightly different from those which provides Ju:

 1. Actually not on this point as I don't have a strong opinion. Only those metrics are quite space consuming, so it should be displayed in minimum requirements too - somehow (as 1 day of those metrics for 6 gluster servers takes about 10G)

 2. In this point I agree with Ju. However if it's not difficult I vote for putting those data back automatically when the cluster is managed again. It simplifies the retention policy as the archive will not be really needed anymore.

 3. I am really curios here about Ju comment. I think alerts are the most critical and so we should focus on them. In best case keep them as long as they are valid. On the other hand notifications/events and logs are not so important and so they could be deleted. I am not sure about time periods, how long it should be kept. Well, let's say:
    - alerts - 1 year (of forever as there should not be much active alerts)
    - events, clearing alerts and logs - 1 month

 4. This depends how we will decide the point 2. Following presume that it will not be automated.
I agree with communicating exact location during un-manage task. However at the same time it could be useful to have documented a general location where all those archives are.
Whatever we choose, it will be good to let user know that those archives could be really big. At the same time I think, it should be user who decides, if he/she wants those archives or not.

 5. I agree with Ju on this point. If it's possible to retain the same cluster id for the same cluster then go for that.

**Comment by shtripat** [comment]
1. At this moment thats how it is maintained and if admin feels that archive of no issue they can always delete the same.
2. Getting back data in case cluster is managed again, has a technical limitation at the moment and need to be explored on how it should be merged with current data which starts coming from cluster the moment it is imported again.
3. Agree. Lets hear from others on this and based on thoughts it could be changed as an event (as @nthomas-redhat says its a user triggered action so an event suffices)
4. Lets hear from others on this and do the required changes if any suggested
5. at the moment if the cluster is un-managed and imported again the cluster's integrtaion-id remains same. But if cluster gets expanded before re-import in this scenario, we need to look for the consequences.

comments @r0h4n @nthomas-redhat @julienlim @gnehapk

**Comment by shtripat** [comment]
There is another thought came up that, why not provide an option in UI to decide if admin wants to retain (archive) the monitoring data or delete it. If retain, then archive would happen else old data would just be wiped out. Thoughts??

**Comment by julienlim** [comment]
@shtripat We can certainly prompt user to Retain or Permanently Delete the monitoring data.  It's yet one more thing a user has to do or think about.  If we believe the archive data is possibly fairly large in term of disk usage, then it may be a good idea to do so.

**Comment by r0h4n** [comment]
@julienlim @shtripat  any updates on this?

**Comment by shtripat** [comment]
@julienlim if UX provides a dialog to show the message, backend side we can implement a flag to capture whether to delete the monitoring data. Based on the value set for the flag, the graphite data would be either deleted or archived.

**Comment by julienlim** [comment]
@shtripat @gnehapk We've added the option to delete/retain the telemetry (monitoring) data in the Unmanage flow -- see https://redhat.invisionapp.com/share/8QCOEVEY9#/273239640_Clusters-Unmanage_Cluster.

**Comment by shtripat** [comment]
@gnehapk @shirshendu ^^^. This would need a UI change as well as API change I feel.
Please check...

**Comment by anmolsachan** [comment]
@r0h4n. Sure I will.

**Comment by shtripat** [comment]
@r0h4n do we want to do this other un-manage refactor PR?
I already have the changes in place and need verification for this.
