### ISSUE TITLE
Cluster wide flows (Import, Expand, Unmanage) should fail if any node in cluster is DOWN

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#828]
Before running flows like Import, Expand, Unmanage cluster, check if any node in the cluster is DOWN, if yes then dont run the flow and fail with appropriate error msg

**Comment by r0h4n** [comment]
I should have been more clear, we dont need to ping the nodes, we only need to load their NodeContext and check if NodeContext.status is not "down" for any nodes, fail import if any NodeContext.status is "down"

**Comment by GowthamShanmugam** [comment]
@r0h4n if node is down or node_agent is down, then node agent status is not moved to downstate. TTl is just deleting the node status entry from etcd. ttl value is deleting the node status after 150 sec. So status is always up only. Because when node-agent is down or node itself down then no way to update the info in etcd.

**Comment by GowthamShanmugam** [comment]
And we have to handle both the situation node_agent down and node down, in both the case we can't allow import flow
