### ISSUE TITLE
Use human readable name as cluster's integration_id

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#888]
Currently in tendrl we use an UUID as cluster's integration_id and if multiple clusters maintained by tendrl it becomes tough to identify the clusters.

There is a suggestion to use human readable name as integration_id for clusters. So the flow to use a human readable name integration_id for cluster would be something like below

1. While node agent detects a cluster which is ready for import, it creates a UUID as temporary detected integration_id for cluster and creates an object `/clusters/{detected-integration-id}` in etcd with `is_managed` value as `no`
2. When UI triggers the import for this cluster the dialog thrown for import cluster would list this detected_cluster_id and user needs to provide a human readable integration_id value in the dialog. If user doesnt provide a human readable name in dialog the existing detected_integration_id remains as final integration_id for the cluster then onwards. May be UI should shown a warning on the dialog regarding the same saying `If no human readable name provided the detected_integration_id would remain as identifier for the cluster and later it wont be possible to change`.
3. UI submits the import cluster request with a flag saying if the detected_cluster_id was replaced with human readable name and the new integration_id. API layer adds a check to find if a cluster with given new integration_id in request, already exists. If so API raises an error saying cluster with this name already exists. This check should happen only if UI send the flag `detected_integration_id_overriden` as `yes`
4. In back-end the import cluster flow adds a pre check atom to do the check for pre-existence of cluster with new `integration_id` in parameters and fail if so. This pre check also runs only if `detected_integration_id_overriden` is set as `yes` in request.
5. The import cluster flow replaces the object `/clusters/{detected_integration_id}` with `/clusters/{human_readable_integration_id}` in etcd based on `detected_integration_id_overriden` field set as `yes`. If the field `detected_integration_id_overriden` is not set as `yes` in request the old `/clusters/{detected_integartion_id}` remains as is.
6. After this import flow runs as usual and continues.

With this there are no other changes required at back-end or any other components and it should be seamlessly working with human readable ntegration_id for cluster.

@r0h4n @nthomas-redhat @gnehapk @shirshendu @GowthamShanmugam @cloudbehl comments/thoughts?

@julienlim if we go ahead with this model, we would need UX changes for the import cluster dialog to capture the human readable integration_id for cluster.

Lets have all the discussion points captured here and go ahead based on the decision taken.

**Comment by r0h4n** [comment]
Thanks @shtripat , Here's my take 
UI:
- Validate the "Cluster.short_name" and ensure it contains only alphabets
- Calls the ImportCluster API with this additional param.

API:
- Validates "Cluster.short_name" based on definitions (not required now) 
- Creates a Tendrl job for "ImportCluster" flow

Backend:
- If "Cluster.short_name" found in  "ImportCluster" flow then do below steps
- This attribute should be called "Cluster.short_name"  (validation, short_name will be only alphabets, no other symbols, due to graphite/etcd limitations) (validate, uniqueness)
- If "Cluster.short_name" then ask provisioner to set Cluster.integration_id == Cluster.short_name and also set the value of etcd tag "indexes/detected_cluster_id_to_integration_id/:detected_cluster_id" == Cluster.short_name
- Now lock the cluster with new integration_id and proceed with import as usual with this new integration_id

**Comment by shtripat** [comment]
Thanks @r0h4n this makes clearer now.
Also with new integration set with short_name, I feel we should set `NS.tendrl_context.integartion_id` with new value. Now only issue I have is how this would reflect for other modules like tendrl-node-agent, monitoring-integration, notifier etc as those services would be already running by the time import cluster starts.

**Comment by shtripat** [comment]
@julienlim we are planning to allow only alphanumeric for cluster name as `.` might create issue in graphite because in graphite a period character is used as separator for directory based hierarchy.

@r0h4n comments above tells to allow only alphabets though.

**Comment by julienlim** [comment]
Ack @shtripat on not going to allow for "." (dots) and will allow for alphanumeric.  What about "-" (hyphen / dash)?

**Comment by shtripat** [comment]
Personally I feel hyphon could be allowed. @nthomas-redhat @r0h4n comments?

**Comment by cloudbehl** [comment]
@shtripat We now follow the "_"(underscore) for replacing the dot(.). I think it's better we the same function in graphite to change space(" ") to ("_").

**Comment by cloudbehl** [comment]
@shirshendu and I discussed this problem and found a solution which will have a less impact.

We follow two Tree structures in collectd 
tendrl -> Cluster -> Volume -> Node -> Brick -> Block Device
tendrl -> Cluster -> Node -> Brick -> Block Device

In which clusters have cluster_id and volume has volume_id and so on.

What we can do is we can add another folder at "clusters" level in the hierarchy named "short_name" or "name"(whatever we want to call it) and inside we will have symlink created from cluster "name" to cluster id in clusters.

**See screenshots for more clarity.**

![screenshot from 2018-04-01 23-50-39](https://user-images.githubusercontent.com/6695156/38176180-eb392be2-3607-11e8-9d18-9ac71f72ef3b.png)

Created the "name" folder
![screenshot from 2018-04-01 23-50-48](https://user-images.githubusercontent.com/6695156/38176182-eba10fe6-3607-11e8-943b-183f90fb7be7.png)

created the symlink using. 
`$ ln -s source destinantion`
![screenshot from 2018-04-01 23-51-09](https://user-images.githubusercontent.com/6695156/38176181-eb6c56ac-3607-11e8-8ac7-5efeb6cee113.png)

I have tried this in my setup and it works fine. The grafana shows the name of a cluster as "ankush123" and the metrics are also getting populated. The only change required is, earlier metrics and templating variable used to start with tendrl.clusters.{cluster_id} and now the metrics will tendrl.name.{short_name}.

![screenshot from 2018-04-01 23-57-35](https://user-images.githubusercontent.com/6695156/38176282-b9daa9f2-3609-11e8-9ceb-9d6cfda6b8ad.png)


Discussing the scenarios.

1. This short_name or name folder will be created in all the scenario(if a user gives the name of a cluster at the time of import or not). This is because of the tendrl metrics will now start with "tendrl.name". 
2. If a user gives the name the symlink will be from a name(the name provided by a user) to the {cluster_id} in clusters otherwise the name will default be integration id.


Discussed and shown the POC to @shirshendu @r0h4n 

@shtripat @nthomas-redhat @julienlim @GowthamShanmugam any comments?

**Comment by shtripat** [comment]
@r0h4n Just by setting `indexes/detected_cluster_id_to_integration_id/:detected_cluster_id` to `short_name` doesnt change the `NS.tendrl_context.integration` on nodes and so during configure monitoring colletcd gets old integration_id only. Also even if we delete `/clusters/{old integration id}` other nodes get that cluster entry back as detected cluster again. 

How can we set the `NS.tendrl_context` with new integration_id (short_name) for all the nodes without restart of node-agent? I feel this will resolve most of the issue. I have seen GI started on the nodes also finds the old value of `NS.tendrl_context.integration`. Can you help on this front?

**Comment by r0h4n** [comment]
@shtripat we dont need to replace Cluster.integration_id, check full comment https://github.com/Tendrl/commons/issues/888#issuecomment-377808239

**Comment by shtripat** [comment]
@r0h4n you mean to go ahead with suggestions which @cloudbehl has added above?
In this case we would need to have a call back to monitoring integration from import cluster flow to create the required symlink for graphite dir (as import cluster gets triggered on storage nodes and graphite symlink creation need to happen on server).

If everybody fine with this approach, I can go ahead with this.
@nthomas-redhat ^^^

**Comment by shtripat** [comment]
For cluster name the regular expression for validation would be `^[a-zA-Z0-9][ A-Za-z0-9_]*$` which allows alphanumeric and `_` character.

**Comment by julienlim** [comment]
@shtripat @r0h4n @cloudbehl @shirshendu @nthomas-redhat @gnehapk @a2batic @GowthamShanmugam 

Symlink suggestion seems reasonable.  Can I assume we will also cleanup (i.e. remove) the symlinks when we unmanage cluster?

**Comment by shtripat** [comment]
@julienlim oh yes. that we should be doing that. Will take care as part this change.

**Comment by gnehapk** [comment]
@shirshendu Can you please mention the updated post data for `/clusters/{clusterId}/import` API?

**Comment by shirshendu** [comment]
Ideally API should be picking up such things dynamically from the definitions, but that isn't currently in place so the following applies:

- Queueing the import job doesn't need a change, we pass on the params from the incoming call to the import job
- We'll need a minor change to cluster details GET API, to add short_name to the whitelist

**Comment by mbukatov** [comment]
The proposal suggests to use user-friendly name both as an id (within tendrl internal datastructures and etcd database) and end user facing interfaces. At first sight, this seems to go against a common practice to have a user friendly name and database id separate, which allows eg. change of the user-friendly name later. Why is that. Also later, @cloudbehl  https://github.com/Tendrl/commons/issues/888#issuecomment-377808239 suggests that in some cases, symlinks could be used. Could someone summarize the final agreement and details?

**Comment by mbukatov** [comment]
I have few additional questions:

* What is a max. length of the user friendly name?
*  What should happen when one unmanages a cluster with readable name, and
  imports it again later with different name, or with uuid? The same applies
  to starting with cluster identified with uuid and then reimporting it with
  custom name.
* Does this affect expand feature in some way it's not obvious at first sight?

**Comment by r0h4n** [comment]
@mbukatov  We have implemented the symlink based approach and not using the short_name as a primary key. So the integration_id is still the unique id for any cluster.

- What is a max. length of the user friendly name?
- There is no max length limitation, but IMO it should be **64 characters**.  (@Tendrl/api @Tendrl/frontend @shtripat)

- What should happen when one unmanages a cluster with readable name, and
imports it again later with different name, or with uuid? The same applies
to starting with cluster identified with uuid and then reimporting it with
custom name.
- **Unmanage cluster will remove all traces of the symlinks and the Cluster.short_name** will also be deleted. So when the user imports it again, he can provide a different short name or choose to go with uuid as it works today (@shtripat )

- Does this affect expand feature in some way it's not obvious at first sight?
- Doesnt affect expand API, we dont allow changing the Cluster.short_name during expand API

**Comment by mbukatov** [comment]
@r0h4n Thanks for the answer.

**Comment by mbukatov** [comment]
I have additional question: when I select a short name for cluster during import, tendrl api calls will still use integration_id to identify a cluster - right? If yes, what is the expected way to translate short name to untegration id and back?

adding @fbalak as this will affect the api tests
